create table asset(
    asset_symbol varchar(50),
    primary key (asset_symbol),
    asset_name varchar(100)
);

create table aggregated_price (
    id bigint generated by default as identity,
     primary key (id),
    asset varchar(50),
    ask_price float(53),
    bid_price float(53),
    currency varchar(50),
    bid_price_source varchar(100),
    ask_price_source varchar(100),
    last_updated_time timestamp(6),
    CONSTRAINT fk_asset_price FOREIGN KEY (asset) REFERENCES asset(asset_symbol),
    CONSTRAINT fk_currency_price FOREIGN KEY (currency) REFERENCES asset(asset_symbol),
    CONSTRAINT unique_asset_curr UNIQUE (asset, currency)
);

create table users (
    user_id bigint generated by default as identity,
    primary key (user_id),
    user_name varchar(255)
);

create table transaction (
    transaction_id bigint generated by default as identity,
    primary key (transaction_id),
    user_id bigint,
    order_type varchar(255),
    asset varchar(50),
    quantity numeric(50,18),
    price float(53),
    currency varchar(50),
    order_executor varchar(255),
    order_created_time timestamp(6),
    order_completed_time timestamp(6),
    order_status varchar(255),
    locked boolean default FALSE,
    last_locked_time timestamp(6),
    CONSTRAINT fk_asset_trans FOREIGN KEY (asset) REFERENCES asset(asset_symbol),
    CONSTRAINT fk_user_trans FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_currency_trans FOREIGN KEY (currency) REFERENCES asset(asset_symbol)
);

create table wallet_balance (
    id bigint generated by default as identity,
    primary key (id),
    user_id bigint,
    asset varchar(50),
    balance numeric(50,18),
    CONSTRAINT fk_asset_wallet FOREIGN KEY (asset) REFERENCES asset(asset_symbol),
    CONSTRAINT fk_user_wallet FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT unique_user_asset UNIQUE (user_id, asset)
);
